#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Rb,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BlowerA,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     BlowerB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BlowerC,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    BallStorage,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    GoalRetainer,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    Kickstand,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Autonomous Program for 4290 GiraPHPHe
 * Moves from parking zone, places ball into small goal, then executes center goal scoring
 **/

/***** INCLUDES *****/
#include "Autonomous/4290-Auto.h" //naturalize RobotC

void init()
{
    bSmartDiagnostics = true; //true to enable smart diagnostic screen
    bCompetitionMode = true; //true to enable competition mode
    displaySplash("GiraPHPHe", "Autonomous", true);
    eraseDisplay();
    gyro_init(HTGYRO);
    ir_init(IR);
    wait1Msec(50);
    nxtbarOn();

    options_reset();

    options_create(0, "START");
    options_add(0, "Parking");
    options_add(0, "Ramp"); //IMPLEMENT!

    //options_create(1, "CENTER GOAL");
    //options_add(1, "Yes");
    //options_add(1, "No");

    //options_create(2, "KICKSTAND");
    //options_add(2, "Yes");
    //options_add(2, "No");

    options_create(1, "MOVE");
    options_add(1, "to 90cm");
    //options_add(1, "60 cm");
    options_add(1, "No");

    options_create(2, "WAIT");
    options_add(2, "0 s");
    options_add(2, "5 s");
    options_add(2, "10 s");

    options_create(3, "LOGGING");
    options_add(3, "On");
    options_add(3, "Off");

    options_display("LASA 4290","READY!");
    wait10Msec(100);

    //STORE OPTIONS DETAILS
    //if logging is on
    if (options_get[3] == 0) { ir_loggingEnabled = true; }
    else                     { ir_loggingEnabled = false; }

    return;
}

task main()
{
    /***** BEGIN Mecanum Field Oriented Drive Test *****/
    init();
    //auto_init();
    StartTask(gyro_calibrate, 8);
    StartTask(ir_calibrate, 8);
    StartTask(displaySmartDiags, 255);
    if (bCompetitionMode) {waitForStart();}

    //WAIT if requested
    if (options_get[3] != 0) { wait10Msec(500 * options_get[3]); }

    //auto_moveDownRamp();
    //auto_rampToParking();

    //True for new IR, false for old
    float zone = auto_placeCenterGoal(true);
    servo[BallStorage] = 200;
    wait1Msec(1000);
    if (options_get[2] == 0) { auto_centerGoalToLarge(zone); }
    //Release ball
    wait1Msec(1000);

    //auto_kickstandFromCenterGoal(zone);

    //kill everything
    ir_stopLogging();
    StopAllTasks();
}
