#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTGYRO,             sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Rb,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BlowerA,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     BlowerB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BlowerC,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_2,    BallStorage,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    GoalRetainer,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    Kickstand,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/***** DEFINES *****/
//#define _FORCE_DEBUG //Uncomment to force using debug (non-optimized) mode
//#define _DISABLE_JOYDISPLAY //Uncomment to disable joystick display
#define _ENABLE_LCDDISPLAY //Uncomment to enable live NXT LCD display


task main()
{
    bool toggleinfeed = false;
    bool infeedforward = true;
    TNxtButtons lastnNxtButtonPressed = nNxtButtonPressed;
    nxtDisplayCenteredTextLine(2, "Blower Program");
    nxtDisplayCenteredTextLine(3, "Center-Bl");
    nxtDisplayCenteredTextLine(4, "Left-InBack");
    nxtDisplayCenteredTextLine(4, "Right-InForward");
    while (true)
    {
        if (nNxtButtonPressed == kRightButton && lastnNxtButtonPressed != kRightButton){
            toggleinfeed = !toggleinfeed;
            if(toggleinfeed)
                infeedforward = true;
        }
        if (nNxtButtonPressed == kLeftButton && lastnNxtButtonPressed != kLeftButton ){
            toggleinfeed = !toggleinfeed;
            if(toggleinfeed)
                infeedforward = false;
        }
        /***** Blower Control *****/
        if (nNxtButtonPressed == kEnterButton){
            motor[BlowerA] = 100;
            motor[BlowerB] = 100;
            motor[BlowerC] = 100;
        }
        else{
            motor[BlowerA] = 1;
            motor[BlowerB] = 1;
            motor[BlowerC] = 1;
        }
        /***** Intake Control *****/
        if (toggleinfeed){
            if(infeedforward)
               motor[Intake] = 100;
            else
               motor[Intake] = -100;
        }
        else{
            motor[Intake] = 0;
        }
        lastnNxtButtonPressed = nNxtButtonPressed;
    }
}
