#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //inclusion of joystick control

task main()
{
	while (true == true)
	{
		getJoystickSettings(joystick); //get joystick settings
		motor[left] = joystick.joy1_y1; //joystick 1 makes left motor move
		motor[right] = joystick.joy1_y2; //joystick 1 makes right motor move

	}
}
