#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Rt,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Rb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lt,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lb,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/***** DEFINES *****/
#define _FORCE_DEBUG //Uncomment to force using debug (non-optimized) mode
//#define _DISABLE_JOYDISPLAY //Uncomment to disable joystick display
#define _ENABLE_LCDDISPLAY //Uncomment to enable live NXT LCD display

/***** INCLUDES *****/
#include "../lib/naturalization.h" //naturalize RobotC
#include "../lib/drive.h" //drive trains

/***** STATICS *****/
static bool competitionmode = false; //set to true to wavoid waiting for FCS
static float k_deadband = 15;
static float kx = 1; // strafe tuning constant
static float ky = 1; // forward/rev tuning constant
static float kc = 1; // spin tuning constant

/***** VARIABLES *****/
TJoystick joystick;

void init()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	eraseDisplay();

	wait1Msec(50);
  return;
}

task main()
{
	/***** BEGIN Mecanum Arcade Drive Test *****/
  init();
  float x, y, c; // frw/rev, strafe, spin
  if (competitionmode) {waitForStart();}

  while (true)
  {
  	/***** Proportional Motor Control *****/
  	getJoystickSettings(joystick); //get all joystick statuses

  	x = joystick.joy1_x1; //forward, reverse
  	y = joystick.joy1_y1; //strafe
  	c = joystick.joy1_x2; //spin

  	motor[Lt] = ky*y + kx*x + kc*c;
  	motor[Rt] = ky*y + kx*x + kc*c;
  	motor[Lb] = ky*y + kx*x + kc*c;
  	motor[Rb] = ky*y + kx*x + kc*c;
  }
}
