#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     HTSMUX,              sensorI2CCustom)
#pragma config(Sensor, S4,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Rb,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BlowerA,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     BlowerB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BlowerC,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_2,    BallStorage,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    GoalRetainer,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    Kickstand,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    TouchSensor,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../drivers/hitechnic-sensormux.h"
#include "../drivers/lego-touch.h"
#include "../lib/naturalization.h" //naturalize RobotC
#include "../lib/drive.h" //drive trains
#include "../lib/options.h" //splash screens

void init()
{
  bSmartDiagnostics = true; //true to enable smart diagnostic screen
  bCompetitionMode = true; //true to enable competition mode
  displaySplash("GiraPHPHe", "PID Test", true);
  eraseDisplay();
  wait1Msec(50);
  nxtbarOn();
}

task main()
{
  init();
  StartTask(displaySmartDiags);

  float error = 0;
  float integral = 0;

  clearTimer(T1);
  nMotorEncoder[Rb] = 0;
  while(abs(nMotorEncoder[Rb]) < 10000)
  {
    wait1Msec(10);
    motor[Rb] = 60;
    float go = ramp_pid(10000, nMotorEncoder[Rb], (float)time1[T1] / (float)1000, error, integral);
    nxtDisplayCenteredBigTextLine(4, "%f", go);
    clearTimer(T1);
  }
  motor[Rb] = 0;

  nxtDisplayCenteredBigTextLine(4, "%f", nMotorEncoder[Rb]);
  wait10Msec(100);
}
