#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //include joystick

task main()
{
	while ( true )
	{
		getJoystickSettings(joystick); //read joysticks
		motor[left] = joystick.joy1_y1; //make robot move left
		motor[right] = joystick.joy1_y2; //make robot move right
		motor[intake] = joy1Btn(6)*100; //button six is intake
		if (joy1Btn(5) == 1){motor[lift] = 100;} //button 5 and 7 is lifter
		else if (joy1Btn(7) == 1) {motor[lift] = -100;}
		else { motor[lift] = 0; }
	}
}
