#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Sensor, S3,     ArmLimit,       sensorTouch)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     ArmB,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ArmA,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DriveLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DriveRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     ArmC,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    ArmRelease,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    ManipL,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    ManipR,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    Auto,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// RobotC pre-generated schematic above.  Do NOT attempt to change manually
// NOR move to another locale in code.

//////////
// INFO //
//////////

// This is an implementation of the Faux drive system on 4290.
// Oh, an there's no .h file, because that would be pointless.


/////////////
// STATICS //
/////////////

static float d_lastbasket = 6500;
static float d_firststop = 7000;


//////////////////////////////
// DEFINITIONS AND INCLUDES //
//////////////////////////////

#define _DEBUG_  //define this to activate debug info

#include "TestFaux_Functions.c"


///////////////
// VARIABLES //
///////////////

bool killall = false;
string state = "Initializing";


/////////////
// METHODS //
/////////////

//Places the block in a bucket.
void placeBlock()
{
	servo[Auto] = 240;
	wait1Msec(1000);
	servo[Auto] = 15;
	wait1Msec(1000);
}

//Displays the state of autonomous with debug information
task DisplayThread()
{
	while(!killall)
	{
		nxtDisplayString(2, state);
		nxtDisplayString(3, "%d",nMotorEncoder[DriveLeft]);
		nxtDisplayString(4, "%d",nMotorEncoder[DriveRight]);
		nxtDisplayString(5, "%d",SensorValue[IR]);
		nxtDisplayString(6, "%d", HTIRS2readACDir(IR));
	}
}

/////////////////
// MAIN THREAD //
/////////////////

task main()
{
	// *** INITIALIZE ***
	state = "Initializing";
	tHTIRS2DSPMode _mode = DSP_1200;
	if (HTIRS2setDSPMode(IR, _mode) == 0)
	{
		#ifdef _DEBUG_
		StopAllTasks(); //Did not set mode sucessfully
		#endif
	}
	//Reset encoders
	nMotorEncoder[DriveLeft] = 0;
	nMotorEncoder[DriveRight] = 0;
	bFloatDuringInactiveMotorPWM = false; //the motor will not coast when power is applied
	nMotorPIDSpeedCtrl[DriveLeft] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[DriveRight] = mtrSpeedReg;
	StartTask(DisplayThread);
	state = "Waiting";
	waitForStart();

	// *** MOVE FORWARD ***
	state = "Move Forward";
	//While encoders are both less than 6500 and we dont have an ir value, go forward
	while ((abs(nMotorEncoder[DriveLeft]) < d_lastbasket && abs(nMotorEncoder[DriveRight]) < d_lastbasket)){
		motor[DriveLeft] = 50;
		motor[DriveRight] = 50;

		//Read IR, break on 6.
		if (HTIRS2readACDir(IR) == 6){
			break;
		}
	}

	//If we either reach the end (6500) w/o good IR or reach ir, place block
	motor[DriveLeft] = 0;
	motor[DriveRight] = 0;
	placeBlock();

	state = "Finish Moving";

	while((nMotorRunState[DriveLeft] != runStateIdle) || (nMotorRunState[DriveRight] != runStateIdle)) { state = "I M IN WHILE"; }
	state = "KILLED!";
	motor[DriveLeft] = 0;
	motor[DriveRight] = 0;
	killall = false;
}
